apiVersion: v1
kind: Service
metadata:
  name: {{ include "dt-studio.fullname" . }}
  labels:
    {{- include "dt-studio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: websocket
      port: {{ .Values.wsport }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "dt-studio.selectorLabels" . | nindent 4 }}
